// Dummy data sesuai dengan struktur database

export const categories = [
  { id: 1, name: 'Skincare', slug: 'skincare', icon: '🧴', count: 48 },
  { id: 2, name: 'Makeup', slug: 'makeup', icon: '💄', count: 36 },
  { id: 3, name: 'Herbal & Jamu', slug: 'herbal-jamu', icon: '🌿', count: 24 },
  { id: 4, name: 'Haircare', slug: 'haircare', icon: '💇‍♀️', count: 18 },
  { id: 5, name: 'Body Care', slug: 'body-care', icon: '🧼', count: 22 },
];

export const products = [
  {
    id: 1,
    sku: 'SKIN-001',
    name: 'Brightening Vitamin C Serum',
    slug: 'brightening-vitamin-c-serum',
    description: 'Serum vitamin C dengan formula stabil untuk mencerahkan kulit dan mengurangi hiperpigmentasi.',
    shortDescription: 'Serum vitamin C untuk kulit cerah merata',
    categoryId: 1,
    category: 'Skincare',
    brand: 'GlowLab',
    basePrice: 189000,
    salePrice: 159000,
    weightGram: 50,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 95.5,
    trendBadge: 'viral',
    totalSold: 1234,
    stock: 89,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/20/400/500',
      'https://picsum.photos/id/21/400/500',
      'https://picsum.photos/id/22/400/500',
    ],
    rating: 4.8,
    totalReviews: 234,
    tags: ['vitamin c', 'brightening', 'serum', 'skincare'],
  },
  {
    id: 2,
    sku: 'HERB-001',
    name: 'Jamu Kunyit Asam Herbal',
    slug: 'jamu-kunyit-asam-herbal',
    description: 'Jamu tradisional dari kunyit dan asam jawa untuk menjaga kebugaran tubuh.',
    shortDescription: 'Jamu tradisional kunyit asam',
    categoryId: 3,
    category: 'Herbal & Jamu',
    brand: 'HerbalIndo',
    basePrice: 85000,
    salePrice: 75000,
    weightGram: 200,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: true,
    trendScore: 88.2,
    trendBadge: 'trending',
    totalSold: 567,
    stock: 45,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/30/400/500',
      'https://picsum.photos/id/31/400/500',
    ],
    rating: 4.6,
    totalReviews: 89,
    tags: ['jamu', 'kunyit asam', 'herbal', 'traditional'],
  },
  {
    id: 3,
    sku: 'SKIN-002',
    name: 'Hydrating Moisturizer',
    slug: 'hydrating-moisturizer',
    description: 'Pelembab ringan dengan hyaluronic acid untuk kulit yang terhidrasi sepanjang hari.',
    shortDescription: 'Pelembab dengan hyaluronic acid',
    categoryId: 1,
    category: 'Skincare',
    brand: 'DewyLab',
    basePrice: 125000,
    salePrice: 99000,
    weightGram: 50,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 92.3,
    trendBadge: 'best_seller',
    totalSold: 2100,
    stock: 156,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/40/400/500',
      'https://picsum.photos/id/41/400/500',
      'https://picsum.photos/id/42/400/500',
    ],
    rating: 4.9,
    totalReviews: 456,
    tags: ['moisturizer', 'hydrating', 'skincare', 'hyaluronic acid'],
  },
  {
    id: 4,
    sku: 'SKIN-003',
    name: 'SPF 50 PA++++ Sunscreen',
    slug: 'spf-50-sunscreen',
    description: 'Tabir surya dengan tekstur ringan, tidak lengket, dan perlindungan maksimal.',
    shortDescription: 'Sunscreen SPF 50 PA++++',
    categoryId: 1,
    category: 'Skincare',
    brand: 'SunShield',
    basePrice: 135000,
    salePrice: 115000,
    weightGram: 30,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 96.7,
    trendBadge: 'viral',
    totalSold: 3456,
    stock: 234,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/50/400/500',
      'https://picsum.photos/id/51/400/500',
    ],
    rating: 4.7,
    totalReviews: 789,
    tags: ['sunscreen', 'spf', 'uv protection', 'skincare'],
  },
  {
    id: 5,
    sku: 'MAKE-001',
    name: 'Matte Lip Cream',
    slug: 'matte-lip-cream',
    description: 'Lip cream dengan formula matte yang nyaman di bibir dan tahan lama.',
    shortDescription: 'Lip cream matte tahan lama',
    categoryId: 2,
    category: 'Makeup',
    brand: 'Lush Beauty',
    basePrice: 89000,
    salePrice: 69000,
    weightGram: 15,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 85.5,
    trendBadge: 'trending',
    totalSold: 890,
    stock: 67,
    isActive: true,
    isFeatured: false,
    images: [
      'https://picsum.photos/id/60/400/500',
      'https://picsum.photos/id/61/400/500',
    ],
    variants: [
      { id: 101, name: 'Red Velvet', stock: 25, priceModifier: 0 },
      { id: 102, name: 'Pink Blossom', stock: 22, priceModifier: 0 },
      { id: 103, name: 'Nude Beige', stock: 20, priceModifier: 0 },
    ],
    rating: 4.5,
    totalReviews: 123,
    tags: ['lip cream', 'matte', 'makeup', 'lipstick'],
  },
  {
    id: 6,
    sku: 'HERB-002',
    name: 'Temulawak Herbal Drink',
    slug: 'temulawak-herbal-drink',
    description: 'Minuman herbal dari temulawak untuk menjaga kesehatan liver dan daya tahan tubuh.',
    shortDescription: 'Minuman herbal temulawak',
    categoryId: 3,
    category: 'Herbal & Jamu',
    brand: 'HerbalIndo',
    basePrice: 95000,
    salePrice: 85000,
    weightGram: 250,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: true,
    trendScore: 78.5,
    trendBadge: 'hot',
    totalSold: 345,
    stock: 78,
    isActive: true,
    isFeatured: false,
    images: [
      'https://picsum.photos/id/70/400/500',
      'https://picsum.photos/id/71/400/500',
    ],
    rating: 4.4,
    totalReviews: 67,
    tags: ['temulawak', 'herbal', 'health drink', 'jamu'],
  },
  {
    id: 7,
    sku: 'HAIR-001',
    name: 'Hair Growth Serum',
    slug: 'hair-growth-serum',
    description: 'Serum untuk merangsang pertumbuhan rambut dengan bahan alami.',
    shortDescription: 'Serum penumbuh rambut',
    categoryId: 4,
    category: 'Haircare',
    brand: 'HairGro',
    basePrice: 175000,
    salePrice: 149000,
    weightGram: 60,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: true,
    trendScore: 82.0,
    trendBadge: 'trending',
    totalSold: 678,
    stock: 92,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/80/400/500',
      'https://picsum.photos/id/81/400/500',
    ],
    rating: 4.6,
    totalReviews: 145,
    tags: ['hair growth', 'serum', 'haircare', 'rambut rontok'],
  },
  {
    id: 8,
    sku: 'SKIN-004',
    name: 'Retinol Night Cream',
    slug: 'retinol-night-cream',
    description: 'Night cream dengan retinol untuk anti-aging dan regenerasi kulit.',
    shortDescription: 'Night cream retinol anti-aging',
    categoryId: 1,
    category: 'Skincare',
    brand: 'GlowLab',
    basePrice: 245000,
    salePrice: 199000,
    weightGram: 40,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 91.1,
    trendBadge: 'best_seller',
    totalSold: 1567,
    stock: 112,
    isActive: true,
    isFeatured: false,
    images: [
      'https://picsum.photos/id/90/400/500',
      'https://picsum.photos/id/91/400/500',
    ],
    rating: 4.8,
    totalReviews: 234,
    tags: ['retinol', 'night cream', 'anti aging', 'skincare'],
  },
  {
    id: 9,
    sku: 'BODY-001',
    name: 'Body Scrub Coffee',
    slug: 'body-scrub-coffee',
    description: 'Lulur kopi untuk mengangkat sel kulit mati dan menghaluskan kulit.',
    shortDescription: 'Lulur kopi eksfoliasi',
    categoryId: 5,
    category: 'Body Care',
    brand: 'BodyLove',
    basePrice: 95000,
    salePrice: 79000,
    weightGram: 200,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: true,
    trendScore: 75.0,
    trendBadge: 'none',
    totalSold: 456,
    stock: 134,
    isActive: true,
    isFeatured: false,
    images: [
      'https://picsum.photos/id/100/400/500',
      'https://picsum.photos/id/101/400/500',
    ],
    rating: 4.3,
    totalReviews: 78,
    tags: ['body scrub', 'coffee scrub', 'lulur', 'body care'],
  },
  {
    id: 10,
    sku: 'MAKE-002',
    name: 'Foundation HD',
    slug: 'foundation-hd',
    description: 'Foundation dengan coverage medium to full, tahan lama hingga 12 jam.',
    shortDescription: 'Foundation coverage tinggi',
    categoryId: 2,
    category: 'Makeup',
    brand: 'Lush Beauty',
    basePrice: 155000,
    salePrice: 129000,
    weightGram: 30,
    isBpomCertified: true,
    isHalalCertified: true,
    isHerbal: false,
    trendScore: 88.8,
    trendBadge: 'viral',
    totalSold: 2345,
    stock: 156,
    isActive: true,
    isFeatured: true,
    images: [
      'https://picsum.photos/id/110/400/500',
      'https://picsum.photos/id/111/400/500',
    ],
    variants: [
      { id: 201, name: 'Fair', stock: 50, priceModifier: 0 },
      { id: 202, name: 'Medium', stock: 60, priceModifier: 0 },
      { id: 203, name: 'Tan', stock: 30, priceModifier: 0 },
      { id: 204, name: 'Deep', stock: 16, priceModifier: 0 },
    ],
    rating: 4.7,
    totalReviews: 345,
    tags: ['foundation', 'makeup', 'base makeup', 'hd foundation'],
  },
];

// Flash sale items
export const flashSaleItems = [
  { ...products[0], flashPrice: 129000, originalPrice: products[0].salePrice || products[0].basePrice },
  { ...products[2], flashPrice: 79900, originalPrice: products[2].salePrice || products[2].basePrice },
  { ...products[3], flashPrice: 95000, originalPrice: products[3].salePrice || products[3].basePrice },
  { ...products[4], flashPrice: 55000, originalPrice: products[4].salePrice || products[4].basePrice },
];

// Trending keywords dari API
export const trendingKeywords = [
  { keyword: 'Skincare Routine', score: 98, trend: 'up' },
  { keyword: 'Vitamin C Serum', score: 95, trend: 'up' },
  { keyword: 'Jamu Herbal', score: 92, trend: 'up' },
  { keyword: 'Sunscreen', score: 90, trend: 'up' },
  { keyword: 'Retinol', score: 87, trend: 'down' },
  { keyword: 'Lip Tint', score: 85, trend: 'up' },
  { keyword: 'Hair Growth', score: 82, trend: 'up' },
  { keyword: 'Body Scrub', score: 78, trend: 'stable' },
];

// Testimonial data
export const testimonials = [
  {
    id: 1,
    name: 'Sarah Wijaya',
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    rating: 5,
    comment: 'Produknya amazing! Serum Vitamin C beneran bikin kulit glowing. Fast delivery juga!',
    product: 'Brightening Vitamin C Serum',
    date: '2024-01-15',
  },
  {
    id: 2,
    name: 'Budi Santoso',
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    rating: 5,
    comment: 'Jamu kunyit asamnya enak dan manjur untuk kesehatan. Langganan rutin!',
    product: 'Jamu Kunyit Asam Herbal',
    date: '2024-01-20',
  },
  {
    id: 3,
    name: 'Dewi Putri',
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    rating: 4,
    comment: 'Sunscreen ringan di wajah, tidak lengket. Perlindungannya bagus!',
    product: 'SPF 50 PA++++ Sunscreen',
    date: '2024-01-18',
  },
];

// Viral TikTok data
export const viralTikTok = [
  {
    id: 1,
    productId: 1,
    productName: 'Vitamin C Serum',
    views: '2.5M',
    likes: '350K',
    hashtag: '#GlowingChallenge',
    videoUrl: 'https://example.com/video1',
  },
  {
    id: 2,
    productId: 4,
    productName: 'SPF Sunscreen',
    views: '1.8M',
    likes: '220K',
    hashtag: '#SunProtection',
    videoUrl: 'https://example.com/video2',
  },
];

export default {
  categories,
  products,
  flashSaleItems,
  trendingKeywords,
  testimonials,
  viralTikTok,
};